# Generated by Django 3.2.5 on 2021-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='med_name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='price',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='med_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity',
        ),
        migrations.AddField(
            model_name='medicine',
            name='Medicine_Name',
            field=models.CharField(default='Crocin', max_length=200, verbose_name='Medicine Name'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription',
            field=models.CharField(default='Y', max_length=500, verbose_name='Prescription'),
        ),
    ]
