# Generated by Django 3.2.5 on 2021-10-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211005_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(default='Crocin', max_length=200, verbose_name='Medicine Name')),
                ('prescription', models.CharField(default='Y', max_length=500, verbose_name='Prescription')),
                ('Type_of_Sell', models.CharField(max_length=500, null=True, verbose_name='Type of Sell')),
                ('manufacturer', models.CharField(default='Cipla', max_length=500, verbose_name='Manufacturer')),
                ('salt', models.CharField(max_length=500, null=True, verbose_name='Salt')),
                ('mrp', models.IntegerField(default=50, verbose_name='MRP')),
                ('uses', models.CharField(max_length=500, null=True, verbose_name='Uses')),
                ('Side_Effects', models.CharField(max_length=500, null=True, verbose_name='Side Effects')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='medicines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.medicine'),
        ),
        migrations.DeleteModel(
            name='Medicines',
        ),
    ]
