# Generated by Django 3.2.5 on 2021-10-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211007_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Medicine_Name',
            new_name='med_name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='prescription',
        ),
    ]
