# Generated by Django 3.2.5 on 2021-10-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='customer',
            field=models.ForeignKey(default='Anonymous', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer'),
        ),
    ]
