# Generated by Django 3.2.5 on 2021-10-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211007_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='mrp',
            field=models.CharField(default='50', max_length=100, verbose_name='MRP'),
        ),
    ]
