# Generated by Django 3.2.5 on 2021-10-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_medicine_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='mrp',
            field=models.IntegerField(default=50, verbose_name='MRP'),
        ),
    ]
