# Generated by Django 3.2.5 on 2021-10-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_medicine_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='mrp',
            field=models.CharField(default='50', max_length=500, verbose_name='MRP'),
        ),
    ]
