# Generated by Django 3.1.2 on 2021-10-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211020_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.CharField(default='https://newassets.apollo247.com/pub/media/catalog/product/a/z/aza0002.jpg', max_length=200, verbose_name='Images'),
        ),
    ]
