# Generated by Django 3.1.2 on 2021-10-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.CharField(default='https://newassets.apollo247.com/pub/media/catalog/product/a/z/aza0002.jpg', max_length=1000, verbose_name='Images'),
        ),
    ]
